sonar.organization=itsupan
sonar.projectKey=itsupan_sns
sonar.projectName=sns

sonar.sources=src
sonar.tests=src
sonar.exclusions=src/**/*.spec.ts,src/**/*.test.ts,src/**/*.e2e.ts,src/lib/server/db/auth-schema.ts
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts,src/**/*.e2e.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
